# Generated by Django 6.0.1 on 2026-01-27 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('DEP', 'Deposit'), ('WDL', 'Withdrawal'), ('TRF', 'Transfer')], default='TRF', max_length=3),
        ),
    ]
