# Generated by Django 6.0.1 on 2026-01-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction_ref_id_transaction_tx_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/ids/'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='live_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='veifications/selfies/'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
