# Generated by Django 6.0.1 on 2026-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_id_card_photo_account_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kyc_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee'), ('business', 'Business/Self-Employed'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
